apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mysql-exporter
  namespace: kube-system
  labels:
    k8s-app: mysql-exporter
spec:
  selector:
    matchLabels:
      k8s-app: mysql-exporter
  template:
    metadata:
      labels:
        k8s-app: mysql-exporter
    spec:
      containers:
      - image: prom/mysqld-exporter
        imagePullPolicy: IfNotPresent
        name: mysql-exporter
        ports:
        - containerPort: 9104
          protocol: TCP
          name: http
        env:
          - name: DATA_SOURCE_NAME
            value: "exporter:exporter@(192.168.0.193:3306)/" ################注意注意！！！！！！！！！！！，这里是mysql创建的远程连接账号，最后必须加"/"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: mysql-exporter
  name: mysql-exporter
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9104
    nodePort: 30108
    protocol: TCP
  type: NodePort
  selector:
    k8s-app: mysql-exporter
