apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-exporter
  namespace: kube-system
  labels:
    k8s-app: redis-exporter
spec:
  selector:
    matchLabels:
      k8s-app: redis-exporter
  template:
    metadata:
      labels:
        k8s-app: redis-exporter
    spec:
      containers:
      - image: oliver006/redis_exporter
        imagePullPolicy: IfNotPresent
        name: redis-exporter
        ports:
        - containerPort: 9121
          protocol: TCP
          name: http
        env:
          - name: REDIS_ADDR
            value: "redis://192.168.0.170:30107" #####这里填写reids的地址
          - name: REDIS_PASSWORD
            value: "root123redis"   ######这里填写redis的密码，如果没设置不需要此参数
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: redis-exporter
  name: redis-exporter
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9121
    nodePort: 30109
    protocol: TCP
  type: NodePort
  selector:
    k8s-app: redis-exporter
