apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager-config
  namespace: prometheus
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m                     ###当告警的状态由firing变成inactive以后还有监听多久才宣告告警解除，主要是解决某些数据在阈值边缘波动情况。
      smtp_from: 'laokiao@163.com'                   ###发送者邮箱
      smtp_smarthost: 'smtp.163.com:465'             ###邮箱的SMTP服务器地址465
      smtp_auth_username: 'laokiao@163.com'		     ###发送者邮箱
      smtp_auth_password: '******'		             ###使用邮箱生成的授权码,并非邮箱密码
      smtp_require_tls: false
    route:                          ###告警内容从这里进入，寻找自己应该用哪种策略发送信息
      group_by: ['alertname']       ###告警应该根据哪些标签分组
      group_wait: 5s                ###同一组告警发送前要等到多久，为了把更多告警一次发送出去
      group_interval: 5s            ###同一组告警间隔多久发送
      repeat_interval: 5m           ###重复告警等待多久再次发送
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: '123@qq.com'                             ###接收者邮箱
        send_resolved: true                      ##当问题解决了是否通知一下
    inhibit_rules:                   ###抑制项，通过匹配源告警来抑制目的告警。如，主机挂了导致数据库，中间件的告警，后续告警是没有意义的，可以直接取消该告警。
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']   ###通过上面的配置，可以在alertname相同的情况下，critaical的报警会抑制warning级别的报警信息。
